### ISSUE TITLE
Adding a new dependency when running dev mode fails

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/svelvet#10]
So if you start svelvet in dev mode and then at any point you add a **new unique node_modules import path**, you'll likely get a runtime error saying that file doesn't exist. The other possibility is that you already had that module installed, but you're referencing a *different* path for the first time. 

This happens because svelvet runs `snowpack` **only once** and we don't track (watch) your source for new import paths. 

### Workarounds

Any time you install a new dependency and import it somewhere in your src, **always restart dev mode**.

### Long-term

It looks like we'll have to track all your import paths in order for svelvet to understand when to run `snowpack` again. This shouldn't be difficult... it's just a bit of extra overhead that we'll have to live with.

**Comment by v0idifier** [comment]
how do you track the import paths? do we just watch `node_modules`?

**Comment by jakedeichert** [comment]
Watching node_modules won't work here because the failure can happen just simply by importing a new path from a dependency you haven't before.

Example:

If import `import { onMount } from 'svelte';` and then start the dev server, things will work.

However, if i change that import to `import { onMount } from 'svelte/internal';`, your app will fail to work because snowpack hasn't generated `dist/web_modules/svelte/internal` yet... which is why restarting the dev server fixes this! Snowpack runs again and generates your complete `dist/web_modules` according to all existing imports.

I think i might take this issue in the next week. I have a plan i want to investigate with babel (part of the snowpack toolchain).

**Comment by FredKSchott** [comment]
Would love to know if you have any ideas on how to improve this flow, I agree it's one downside of the "automatic import scanning" that we do. You can always maintain a "webDependencies" list manually, but that's an extra bit of config and it still requires you to re-run Snowpack when you add something new.

**Comment by jakedeichert** [comment]
I think i have a solution for svelvet. In dev/watch mode, i'll check all imports via a babel plugin (maybe a regex would even work?) and trigger snowpack to run again when it sees a new unique import path. This should prevent dev mode from breaking on people :)

**Comment by jakedeichert** [comment]
I might tackle it this week

**Comment by FredKSchott** [comment]
Nice! We're looking to use https://github.com/guybedford/es-module-lexer for this ourselves, it's WASM and super fast.

**Comment by jakedeichert** [comment]
Ahh, perfect! I'll try that one first :)
