### ISSUE TITLE
Minify on production

### ISSUE THREAD

**Issue by v0idifier** [jakedeichert/svelvet#17]
Would it make sense to use some kind of babel transformation or a whole minifier on production, automatically?

**Comment by jakedeichert** [comment]
I think this does make sense! I actually gave terser cli a try last night and saw really good results.

For now, i'm going to update the readme with DIY instructions for production optimization with terser, but i think short-medium term we should integrate it directly.

**Comment by jakedeichert** [comment]
Here's what i did:

```sh
npm i terser

# Build for production
NODE_ENV=production svelvet

# Minify ALL js dist files
find ./dist -type f \( -name "*.js" \) \
    -exec terser {} -o {} -m -c --module \; \
    -exec echo "Terser minified {}" \;
```

**Comment by v0idifier** [comment]
cool! i am using a Makefile to build a small project i made, that calls this script:
```bash
for i in $(ls dist/*.js dist/**/*.js dist/**/**/*.js); do echo $i && terser $i -o $i; done
```
(my bash skills are bad)

and it works well enough.

**Comment by v0idifier** [comment]
oh we posted our minifier scripts at the same time! hah your's is better though
