### ISSUE TITLE
add file version to url on build

### ISSUE THREAD

**Issue by jeberly** [jakedeichert/svelvet#21]
Project looks great, nice work!

I was testing with a new project and trying to figure out how to add file version to url when building for production so we can cache files forever and change urls when needed. 

I tried adding this to `babel.config.js` file.

```
module.exports = {
  plugins: [
    [
      "snowpack/assets/babel-plugin.js",
      {
        addVersion: true
      }
    ]
  ]
};
```

It didn't add version to outputted files when building for production.  Any ideas on how best to achieve this?

Thanks!

**Comment by jakedeichert** [comment]
Hey! So this maybe sounds like `babel.config.js` isn't being picked up. I'll investigate.

I did try the `addVersion` flag personally, and i ran into an issue where it appended `?undefined` to my imports... meaning it couldn't figure out the `package.json` version in certain cases.

**Comment by jakedeichert** [comment]
Fixed this, but snowpack does have a bug as seen [here](https://github.com/jakedeichert/svelvet/pull/26#discussion_r370462660) which i think is due to nested file imports.

**Comment by jeberly** [comment]
Awesome, thanks for taking a look right away! I will continue to poke around later, loving the idea of this project.
