### ISSUE TITLE
Using Servor For Auto Reload

### ISSUE THREAD

**Issue by theword** [jakedeichert/svelvet#30]
On the Snowpack tutorial, they recommend using servor instead of serve because it has live reload. 

Tutorial (Serve & Run Your Application):
https://www.snowpack.dev/#installing-a-dev-server

The NPM Servor Package:
https://www.npmjs.com/package/servor

However, when I run their command npx servor --reload (or npx servor --reload dist)
It shows up as a blank page, have you tried running svelvet with servor? I'm probably messing up the command or the setup. But it does seem to be an easy way for you to add auto-refresh to the project by using this other dev server with minimum effort.

**Comment by jakedeichert** [comment]
Thanks for telling me about servor. I'll give it a try... the api could be useful for svelvet to start a dev server with live reload.

As to why it's not working for you, i'm not sure yet!

**Comment by jakedeichert** [comment]
So i just gave servor a run with `servor --reload dist` and it loaded on `localhost:8080`. In another tab, i had `svelte` running. On file change, it refreshed the web browser properly. Not sure why you're getting a white page 🤔 


`npm uninstall serve` removed *61 packages*! I think I'll recommend servor in the docs instead.

**Comment by theword** [comment]
Ah, I was making a stupid mistake. 

Awesome! Getting rid of 61 packages is aligned with the philosophy of your project. And with servor now, you get refresh and a standalone package.

**Comment by FredKSchott** [comment]
@jakedeichert haha same here, I had the same thought when @lukejacksonn showed it to me :)

**Comment by jakedeichert** [comment]
Closing this issue in favor of #32

**Comment by jakedeichert** [comment]
@theword released v0.2.0 with servor built in! https://github.com/jakedeichert/svelvet/pull/34
