### ISSUE TITLE
[Feature Request] Include a dev server by default

### ISSUE THREAD

**Issue by FredKSchott** [jakedeichert/svelvet#32]
Note: I still haven't had a chance to play with Svelte/Svelvet myself, this is just feedback based on my review of: https://github.com/pikapkg/snowpack/pull/182

I always have trouble with workflows that ask me to run two long-running CLIs at once. If watch mode is always meant for local development, and you'll always want a local dev server during local development, then it may be nice to provide some simple built-in dev server like servor when you start Svelvet in watch mode so that your users only need to run one command.

Alternatively: You could also look for a "svelvet:serve" script in the user's package.json and always run that when you watch. That would be a little more work than having a server run by default, but it would also allow your users to configure their server to their hearts content. Passing server options through Svelvet feels out of scope for what you're trying to do, so I'd probably recommend this one.

**Comment by jakedeichert** [comment]
Yeah, my plan is to run servor in dev mode!

**Comment by jakedeichert** [comment]
Switched the docs and example projects on master to use servor! https://github.com/jakedeichert/svelvet/commit/d7bc805fabaa35715764100f0b62d63b1e89fb40
