### ISSUE TITLE
what happens to the CSS?

### ISSUE THREAD

**Issue by sw-yx** [jakedeichert/svelvet#36]
i may be missing something as nobody seems to be asking this.. but what happens to the compiled css? you run `svelte.compile` and then only output the `js.code`. i dont see the `css: true` compiler option enabled. am I missing something?

**Comment by jakedeichert** [comment]
So the [default](https://svelte.dev/docs#svelte_compile) is `css: true` which means svelte embeds the css into the js output. At runtime, style tags are created in the DOM and the css text is injected there. 

Here's what it looks like in a [production build](https://github.com/jakedeichert/svelvet/blob/e7db092e399b63cbd2c36dacc40d6c071778b3f1/tests/snapshot/dist/components/Header.js#L41) (`tests/snapshot/dist/components/Header.js`).


This should be good enough for most use cases, but I have a feeling people will want svelvet to output css files at some point. However, that means svelvet will have to modify the svelte js output to inject link tags into the DOM likely... not too difficult :) but just means there's another config option that has to be added.

**Comment by jakedeichert** [comment]
This maybe should be documented...

**Comment by sw-yx** [comment]
ohh i missed that the default is `true` because in the Svelte REPL it's false. got it

**Comment by jakedeichert** [comment]
Documented in the README FAQ section: https://github.com/jakedeichert/svelvet#what-happens-to-the-component-css
