### ISSUE TITLE
restart after npm installs?

### ISSUE THREAD

**Issue by mvolkmann** [jakedeichert/svelvet#60]
Is it necessary to restart svelvet after an npm install in order to get it to bundle the new dependency? It's seems like it is. The Snowpack docs say this in the section "Run After Every Install":

  /* package.json */
  "scripts": {
    "prepare": "snowpack"
  }
You can optionally add “snowpack” as a "prepare" script to your package.json and npm/yarn will automatically run it after every new dependency install. This is recommended so that new dependencies are automatically included in your web_modules/ directory immediately.

Is there a way to do this with svelvet?

**Comment by moitias** [comment]
Svelvet runs a full clean & build of dist on every startup which does include snowpack (as far as I understand). You should be able to see it in the early part of the logs, something like this: 

> Building web_modules with snowpack...
> - snowpack installing...
> √ snowpack installed: module, module, svelte/internal [1.60s].

 That is, restarting svelvet should be enough after adding new packages.

**Comment by jakedeichert** [comment]
@moitias is correct, svelvet handles running snowpack for you! You don't need to do anything other than rebuild your project using svelvet.

However, in dev/watch mode, you don't even need to restart svelvet anymore. [v0.3.3](https://github.com/jakedeichert/svelvet/releases/tag/v0.3.3) included support for finding missing web_modules (via looking for new import statements) which triggers snowpack to be ran again.
