### ISSUE TITLE
Allow excluding certain files

### ISSUE THREAD

**Issue by Evertt** [jakedeichert/svelvet#64]
I'm using tailwindcss to compile my css code, so I don't need or want svelvet to copy my css files to the dist folder. But there seems to be no way to turn that off. Can you please add a way to communicate to svelvet to ignore those files? Either through a command argument, or through a config setting somewhere?

Maybe you could actually get it from snowpack? Since snowpack can already be configured with an `exclude` option.

**Comment by jakedeichert** [comment]
A way to do this is definitely needed.

I was actually thinking recently that copying everything inside `src` to `dist` may not make sense in most cases and it's not as efficient as it could be. I was thinking maybe the `src` directory could just hold the js/svelte scripts and a `public` directory would be where we keep all our static resources like images and css files. Then `dist` would probably be moved into `public/dist` so we can just serve/deploy the entire `public` directory. This would mean no more need to copy all assets to a different directory all the time.

Then we likely wouldn't need an excludes option at all I think! Unless people want to exclude certain scripts from being transpiled.

**Comment by Evertt** [comment]
Well in my project that would still be a little weird. Since my css does need to go through a compilation step, so it would make the most sense to have my css live in the `src` directory and the compiled css be output to the `dist` directory.

If I would do what you're suggesting then that would mean that my uncompiled css is publicly accessible, which I'd rather not have.

**Comment by jakedeichert** [comment]
You would be able to keep your css in the `src` directory, but svelvet would **no longer copy it** to dist. I think this sounds like what you wanted?


- `src/` - svelvet looks for and compiles svelte files & copies js files to `public/dist/`
- `public/` - all your static public assets that will be served/deployed
- `public/dist/` - svelvet's build directory

Other compilers like tailwind can then compile your `src/css` files to whatever directory inside public you want to output to. Your uncompiled css can remain living inside `src/` and will not get copied to `public`.

Let me know if you still see issues with this.

**Comment by Evertt** [comment]
> Let me know if you still see issues with this.

Nope, that sounds good to me.
