### ISSUE TITLE
Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by ethantran** [jakedeichert/svelvet#70]
Hey, svelte noob here. I get this error when running command in dev. As a result, only one component is in the dist components folder when there should be four.

```
Failed to compile with svelte: src/components/Support.svelte
{ [Error: EEXIST: file already exists, mkdir 'public/dist/components']
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: 'public/dist/components' }

/*... same with other components ...*/
```

<img width="166" alt="Screen Shot 2020-03-21 at 12 13 38 PM" src="https://user-images.githubusercontent.com/3276358/77232177-7367a100-6b6d-11ea-8c6c-ce127a07fbb0.png">

**Comment by jakedeichert** [comment]
@ethantran hmmm, really weird. I haven't seen this yet.

Can you run the example project and see if it produces the same error?

To figure this out, i might need a minimum reproducible example to test locally.

**Comment by ethantran** [comment]
I was using your example with a few extra components. I fixed it out though. Updating node from 10.6 to 11.15 fixed it. You could probably reproduce it if you switch to 10.6 if you want.
