### ISSUE TITLE
TypeScript complains when HTML references imports

### ISSUE THREAD

**Issue by mvolkmann** [jakedeichert/svelvet#71]
When I configure the use of TypeScript as shown in the docs, it complains if the HTML section of a Svelte component references anything defined in the script section.

I ran the following npm installs:

```
npm install -D svelte-preprocess typescript
npm install lodash
```

I created a default `tsconfig.json` file by entering `npx tsc --init`.

I changed my npm scripts in `package.json` to:

```json
  "scripts": {
    "build": "NODE_ENV=production svelvet --preprocess preprocess.js",
    "dev": "svelvet --preprocess preprocess.js"
  },
```
Here is my very simple `src/App.svelte` file:

```html
<script lang="typescript">
  import _ from '/web_modules/lodash';

  let name: string = 'Svelvet';

  function add(n1: number, n2: number): number {
    return n1 + n2;
  }

  const sum = add(2, '3');
</script>

<h1>Hello, {_.startCase(name)}!</h1>

<label>
  Name
  <input bind:value="{name}" />
</label>

<div>sum = {sum}</div>
```

When I enter `npm run dev` I get the following output:

```
SVELTE WARNING (src/App.svelte) -> '_' is not defined
12: </script>
13:
14: <h1>Hello, {_.startCase(name)}!</h1>
                ^
15:
16: <label>
```

Note that it doesn't think `_` is defined AND it doesn't flag that I pass a string as the second argument to the `sum` function.

Am I missing some configuration?

**Comment by jakedeichert** [comment]
> Am I missing some configuration?

Hmmmm, i'm not actually sure. I haven't used [svelte-preprocess](https://github.com/kaisermann/svelte-preprocess#readme) personally, so I'm not sure if that's expected or not.

You may need to file an issue over there.

**Comment by mvolkmann** [comment]
I changed the lodash import to this:

```js
import _ from 'lodash';
```
When I enter "npm run devp" I get `'_' is not defined`. However, this only happens when I use preprocessing.

See the repo at https://github.com/mvolkmann/svelvet-demo.
`package.json` defines the npm scripts `dev` and `devp` (uses preprocessing).
If I rename `App.svelte` to `App-preprocess.svelte` and rename `App-works.svelte` to `App.svelte` and enter `npm run dev`, it finds lodash fine and everything works.
So it seems just adding the use of preprocessing messes up the lodash import somehow.

**Comment by jakedeichert** [comment]
Your tsconfig.json is messing with svelte-preprocess it seems. I just got it working locally.

See your [preprocess.js file has target set to 2019](https://github.com/mvolkmann/svelvet-demo/blob/82e355d48311d3c0570049d75053ad536523f7c9/preprocess.js#L7).

Your tsconfig has [target 2015 and module set to commonjs](https://github.com/mvolkmann/svelvet-demo/blob/82e355d48311d3c0570049d75053ad536523f7c9/tsconfig.json#L5-L6).

Either delete the tsconfig.json OR change these values to be:

<img width="331" alt="Screen Shot 2020-04-04 at 1 01 44 AM" src="https://user-images.githubusercontent.com/1631044/78419089-01cd2f80-7610-11ea-81b5-7882a7f48744.png">

**Comment by jakedeichert** [comment]
Just merged an example tsconfig to prevent people from running into this in the future 👍

**Comment by mvolkmann** [comment]
I made change you suggested in my repo. The code builds and runs file. But it still doesn't flag TypeScript errors. For example, in `App.svelte` I pass a `number` and a `string` to the `add` function, but that requires two numbers. And I put the result in a variable with a type of `string`, but the `add` function returns a `number`. So it doesn't seem that it is really using the TypeScript preprocessor.

**Comment by jakedeichert** [comment]
> But it still doesn't flag TypeScript errors.

Ahhh i see. I tried this locally and figured it out.

You'll need to disable the `transpileOnly` [option here](https://github.com/jakedeichert/svelvet/blob/c3b271a649ec3e9ecd2d54a518ee347cc7948c01/tests/snapshot-preprocessors/my-preprocessors.js#L11). Then you should see errors being logged.


<img width="1176" alt="Screen Shot 2020-04-04 at 9 19 15 PM" src="https://user-images.githubusercontent.com/1631044/78464657-01896e80-76ba-11ea-9eb8-3e07c5b180b9.png">
