### ISSUE TITLE
Extremelly long build time with tailwind

### ISSUE THREAD

**Issue by gawlk** [jakedeichert/svelvet#73]
Hi,

So I've been trying to integrate Tailwind CSS with Selvet, I think I managed to have something working but it really tooks forever to build, is it normal ? I'm really new to snowpack so I'm not sure if I'm doing everything correctly

Anyway here's a little repo with what I have currently: https://github.com/gawlk/svelvet-tailwind-issue

**Comment by jakedeichert** [comment]
Thanks for posting a repo for me to check. I might be able to look into it this weekend 👍 

Since you're using svelte-preprocess and tailwind, it's unlikely anything to do with svelvet. The preprocess logic runs on each `.svelte` file and I'm assuming that's what is taking so long.

**Comment by gawlk** [comment]
But there is only one `.svelte` file and on my other repo `tailwind` is very fast so I don't know. If you have another way to do this please tell, like I said I'm very new to this `snowpack` world haha

**Comment by gawlk** [comment]
Ok, so I just gulp-ed it all and it works perfectly now

If anyone is interested, here's how: https://github.com/gawlk/svind/tree/svelvet

**Comment by jakedeichert** [comment]
Glad you figured it out.

I actually spent an hour last night trying to find out what was going on here.

If I disable the [tailwindcss postcss plugin](https://github.com/gawlk/svelvet-tailwind-issue/blob/fb6e84af45e02ec60f26408037ba85e2f5cf47a7/preprocess.js#L30), the build actually completes. Something with that plugin is causing issues and would need to be debugged further.

As you can [see here](https://github.com/jakedeichert/svelvet/blob/3379135314132b6cb174a069a31f5bd6b25363e7/src/index.ts#L68-L77), svelvet doesn't do anything weird with the preprocessors... just passes them to the svelte preprocess step.

Anyway, building tailwind outside of svelte is actually exactly what i would have done too. It seems like it doesn't need to run on file change, so it makes sense to run it only once.

**Comment by gawlk** [comment]
Thank you for your time ! It must be an issue with `svelte-preprocess` then, I have boilerplate where I use Svelte with Tailwind and PostCSS without any issue.

It's true, it makes things simpler and cleaner and faster since we don't build 2xx xxx lines of CSS on each save haha
