### ISSUE TITLE
confused about imports

### ISSUE THREAD

**Issue by mvolkmann** [jakedeichert/svelvet#75]
It's not clear to me when I need to include `/web_modules/` in import statements.
My simple app has the following two `.svelte` files.
It seems that I cannot use `/web_modules/` when importing lodash,
but I must include it when importing date-fns.
Does that make sense?

src/App.svelte
```html
<script>
  import _ from 'lodash';
  import DateDisplay from './DateDisplay';

  let name = 'Svelvet';
</script>

<h1>Hello, {_.startCase(name)}!</h1>

<label>
  Name
  <input bind:value={name}>
</label>

<DateDisplay />
```

src/DateDisplay.svelte
```html
<script>
  import {format} from '/web_modules/date-fns.js';
</script>

<div>
  Today is {format(new Date(), 'MMM dd, yyyy')}.
</div>
```

**Comment by jakedeichert** [comment]
You never need to reference `/web_modules` 👍 

I just did this and it worked without issue:

```html
<script>
  import { format } from "date-fns";
</script>

<div>
  Today is {format(new Date(), 'MMM dd, yyyy')}.
</div>
```

**Comment by mvolkmann** [comment]
Thanks!
