### ISSUE TITLE
Typescript files

### ISSUE THREAD

**Issue by iljoo** [jakedeichert/svelvet#80]
Hi! I am stuck on importing files written in Typescript. Say that my `App.svelte` wants to import some TS file like `src/foo.ts` as `import {foo} from './foo'`. Everything compiles just fine, editor gives no error, but ts file gets ignored and doesn't end up in the `dist` folder, thus giving me run time error of 404 `foo.js` not found.

Not sure if this is a Svelvet issue or Snowpack. Maybe someone has ideas/pointers on how to deal with this?

**Comment by jakedeichert** [comment]
Hey! Not sure if you've seen the typescript [preprocessing example here](https://github.com/jakedeichert/svelvet/tree/master/tests/snapshot-preprocessors)?

Typescript **does not** work out of the box. You need to use a preprocessor to handle it just like you do with svelte webpack or rollout. 

Just a forewarning: even though you *can* preprocess to rip ts types out, i still find the whole svelte-typescript story pretty painful at this point in time. I'm personally holding off until the story gets better.
