### ISSUE TITLE
Add a lockfile

### ISSUE THREAD

**Issue by sdemjanenko** [jakedeichert/svelvet#81]
I tried running `npm test` today and I ran into an error because snapshots did not match. I'm not certain if this the snapshots were generated with different versions of dependencies and subdependencies but I could see that causing this error.

This repo should check in either a `yarn.lock` or a `package-lock.json` file so that others can develop on this package with more reliable results.

**Comment by jakedeichert** [comment]
See this thread: https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

There's been so much debate over the years whether packages/libraries should have lockfiles or not. I'm in the camp where only apps should have lockfiles.

If one of the deps changes, I want to find out about it sooner than later, ideally before the user. If snapshots are failing for me or another dev, I just update and review them to make sure nothing unexpected occurred.

**Comment by sdemjanenko** [comment]
So am i supposed to just start by dev-ing by regenerating snapshots, then make my diffs, test again and then if all is good submit a PR with the snapshot changes?

I think it would be useful if a `Development` section was added to the README.

**Comment by jakedeichert** [comment]
@sdemjanenko I just fixed the snapshot tests. 

The snapshot tests should not break often. The problem here is that I forgot to make the svelte + prettier versions absolute at the root of the project. Check out the package.json in my fix commit https://github.com/jakedeichert/svelvet/commit/d92f46d31818a97f0f1ba37aaddf2fc159e94880

**Comment by sdemjanenko** [comment]
Gotcha. Thanks for fixing that. It makes a lot of sense.
