### ISSUE TITLE
Importing images

### ISSUE THREAD

**Issue by benmccann** [jakedeichert/svelvet#85]
The readme says:

> Many of you will not be able to use this if you depend on custom import types

Does that mean you can't import images? That would be necessary in order for the build tool to add a hash to the image name and serve over a CDN. That would be a blocker for me, so I'm hoping it might be able to be supported if it's not already

**Comment by jakedeichert** [comment]
> Does that mean you can't import images?

That's correct. I built svelvet to be an extremely simple build tool, for dev and for production. It only lets you import js and svelte scripts, nothing else.

Thank you for showing interest in the project! I need to update the README to state that I don't plan on developing this any further, as you see in #84 and #83.
