### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by makmm** [jakedeichert/svelvet#9]
When trying to use `onMount` from svelte, (
```html
<script>
	import { onMount } from 'svelte'
	onMount(handleRoute)
</script>
```
) I get the following error in the browser's console
```
Error: Function called outside component initialization svelte.js:20:15
    get_current_component http://localhost:8080/web_modules/svelte.js:20
    onMount http://localhost:8080/web_modules/svelte.js:27
```

Any idea? is there a way to contact you directly? this project is really cool!

**Comment by makmm** [comment]
Importing from `svelte/internal.js` works.
```js
import { onMount } from 'svelte/internal.js'
```

**Comment by jakedeichert** [comment]
Hey, thanks for giving svelvet a try! 

So I just tried this and both ways work for me.

```js
import { onMount } from 'svelte';
// or...
import { onMount } from 'svelte/internal';
```

In the [snapshot test](https://github.com/jakedeichert/svelvet/blob/master/tests/snapshot/src/App.svelte), i also do this and it works.

I think i know what might have happened in your situation... were you running in dev mode by chance? 

There's a known limitation where you are running in dev mode but import a *new* node_modules dependency path for the first time. To fix this, you just need to restart dev mode 🙂 

I'll make an issue for that known bug/limitation separately. It's annoying for first time users but should become unnoticeable to people working in larger projects where they rarely add new/unique import paths.

**Comment by makmm** [comment]
I'm not sure what you meant with the import paths things, but yes, restarting did work!
In fact, snowpack failed to compile my `svelte/internal.js` declarations and failed, but svelvet didn't quit (just printed `Failed to build with snowpack`.) Maybe that should be changed!

**Comment by jakedeichert** [comment]
Check [this issue](https://github.com/jakedeichert/svelvet/issues/10) for the import paths error i mentioned.

As for the `"Failed to build with snowpack"`...  not sure why it failed. The catch shown below shows that the `err` should also have been logged below that message 🤔 

```js
} catch (err) {
        console.log('');
        console.error('Failed to build with snowpack');
        console.error(err);
        console.log('');
}
```

Anyway, glad restarting worked! I'm planning a solution to prevent the need to restart when this happens.

**Comment by makmm** [comment]
No, the error did get logged. I was saying that I think that svelvet should probably quit if something like that happens.

**Comment by jakedeichert** [comment]
Oh, yes that's a good point! Doing that now.

**Comment by makmm** [comment]
thank you so much! such a great project.
